### ISSUE TITLE
Input to reshape is a tensor with 320 values, but the requested shape has 10240

### ISSUE THREAD

**Issue by nahidbrur** [MiguelSteph/cnn-spam-review-detection-tf#1]
<p>For my own word2vec model and data, there occurs the following error after 50 successful steps:</p>
<p>Traceback (most recent call last):
  File "/home/semanticslab/anaconda3/envs/tf3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1327, in _do_call
    return fn(*args)
  File "/home/semanticslab/anaconda3/envs/tf3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1306, in _run_fn
    status, run_metadata)
  File "/home/semanticslab/anaconda3/envs/tf3/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/home/semanticslab/anaconda3/envs/tf3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 320 values, but the requested shape has 10240
	 [[Node: Reshape_Input_X/Reshape = Reshape[T=DT_INT32, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_input_x_0_2, Reshape_Input_X/Reshape/shape)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 181, in <module>
    train_step(x_batch, y_batch)
  File "train.py", line 144, in train_step
    feed_dict)
  File "/home/semanticslab/anaconda3/envs/tf3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/home/semanticslab/anaconda3/envs/tf3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/semanticslab/anaconda3/envs/tf3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/home/semanticslab/anaconda3/envs/tf3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 320 values, but the requested shape has 10240
	 [[Node: Reshape_Input_X/Reshape = Reshape[T=DT_INT32, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_input_x_0_2, Reshape_Input_X/Reshape/shape)]]

Caused by op 'Reshape_Input_X/Reshape', defined at:
  File "train.py", line 95, in <module>
    l2_reg_lambda=L2_REG_LAMBDA)
  File "/home/semanticslab/hdd/development/status_review/cnn-spam-review-detection-tf/scnn_model.py", line 41, in __init__
    self.x_reshape = tf.reshape(self.input_x, [self.input_size*sentence_per_review, words_per_sentence])
  File "/home/semanticslab/anaconda3/envs/tf3/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 2619, in reshape
    name=name)
  File "/home/semanticslab/anaconda3/envs/tf3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/semanticslab/anaconda3/envs/tf3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/semanticslab/anaconda3/envs/tf3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Input to reshape is a tensor with 320 values, but the requested shape has 10240
	 [[Node: Reshape_Input_X/Reshape = Reshape[T=DT_INT32, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_input_x_0_2, Reshape_Input_X/Reshape/shape)]]</p>
<p>Where is the problem and how can i solve it?</>
<p>Thanks in advance</p>

**Comment by MiguelSteph** [comment]
Hi nahidbrur, the problem is about the fact during the training, there may be some generated batch that does whose size is smaller to the batch size. I will fix it. Thank you

**Comment by MiguelSteph** [comment]
Already fixed

**Comment by Estapraq** [comment]
@MiguelSteph  how?
